# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAllFunctionTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_allFunctionTest1(self):
    self.driver.get("https://petclinicapp.azurewebsites.net/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-triangle-right").click()
    self.driver.find_element(By.LINK_TEXT, "Jeff Black").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Testpet")
    self.driver.find_element(By.ID, "birthDate").send_keys("2020-01-01")
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4)").click()
    self.driver.find_element(By.ID, "type").click()
    dropdown = self.driver.find_element(By.ID, "type")
    dropdown.find_element(By.XPATH, "//option[. = 'cat']").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").click()
    element = self.driver.find_element(By.ID, "name")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Bobo")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-triangle-right").click()
    self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-triangle-left").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) span").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) span")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) span").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > td:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > a").click()
  
